### ISSUE TITLE
use as browserify transform results in error

### ISSUE THREAD

**Issue by StephanHoyer** [tivac/mithril-objectify#25]
Create an empty file `empty.js`

```
$ browserify --version
5.11.0

$ browserify empty.js
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){

},{}]},{},[1]);

$ browserify -t mithril-objectify empty.js
/Users/sh/Work/tutory/webapp/node_modules/mithril-objectify/node_modules/falafel/node_modules/acorn/dist/acorn.js:1748
  throw err;
  ^

SyntaxError: Invalid regular expression flag (1:1)
    at Parser.pp.raise (/Users/sh/Work/tutory/webapp/node_modules/mithril-objectify/node_modules/falafel/node_modules/acorn/dist/acorn.js:1745:13)
    at Parser.pp.readRegexp (/Users/sh/Work/tutory/webapp/node_modules/mithril-objectify/node_modules/falafel/node_modules/acorn/dist/acorn.js:3527:38)
    at Parser.pp.readToken_slash (/Users/sh/Work/tutory/webapp/node_modules/mithril-objectify/node_modules/falafel/node_modules/acorn/dist/acorn.js:3318:28)
    at Parser.pp.getTokenFromCode (/Users/sh/Work/tutory/webapp/node_modules/mithril-objectify/node_modules/falafel/node_modules/acorn/dist/acorn.js:3456:19)
    at Parser.pp.readToken (/Users/sh/Work/tutory/webapp/node_modules/mithril-objectify/node_modules/falafel/node_modules/acorn/dist/acorn.js:3190:15)
    at Parser.pp.nextToken (/Users/sh/Work/tutory/webapp/node_modules/mithril-objectify/node_modules/falafel/node_modules/acorn/dist/acorn.js:3182:71)
    at parse (/Users/sh/Work/tutory/webapp/node_modules/mithril-objectify/node_modules/falafel/node_modules/acorn/dist/acorn.js:100:5)
    at module.exports (/Users/sh/Work/tutory/webapp/node_modules/mithril-objectify/node_modules/falafel/index.js:22:15)
    at transform (/Users/sh/Work/tutory/webapp/node_modules/mithril-objectify/index.js:9:12)
    at nr (/usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:230:23)
```

**Comment by StephanHoyer** [comment]
```
$ browserify -t mithril-objectify/browserify empty.js
```
does the trick.

Maybe consider making an alias `index.js` that proxies `browserify.js`

**Comment by tivac** [comment]
Sorry, had a bad example in the readme.

3bc0094d4f381d411377fd613433c192b414f71b fixes it.

I don't want any bundler to be a second-class citizen, so they're all accessed as `mithril-objectify/<adapter>`, where currently `<adapter>` is either `browserify` or `rollup`. It also makes it easy to add new adapters as necessary. I'd like to add one for `webpack` someday, for instance.

Glad you got it sorted out!
